name: Backend Pipeline Example

on:
  push:
    branches:
      - main
    paths:
      - "api/**"
      - ".github/workflows/**"

jobs:
  pipeline:
    uses: wellingtonns/templates-pipeline/.github/workflows/app-pipeline.yml@main
    with:
      app_name: example-backend
      stack_type: backend
      context: api
      image_name: ghcr.io/${{ github.repository_owner }}/example-backend
      kustomize_repository: wellingtonns/kustomize-share
      kustomize_path: app/example-backend
      image_alias: app-image
      update_kustomize: true
      deploy: true
      deploy_ref: main
    secrets: inherit
