name: Frontend Pipeline Example

on:
  workflow_dispatch:
    inputs:
      update_kustomize:
        description: "Atualizar newTag no repositorio kustomize-share."
        required: false
        type: boolean
        default: false
      deploy:
        description: "Aplicar deploy no Kubernetes."
        required: false
        type: boolean
        default: false
  push:
    branches:
      - main
    paths:
      - "app-clinica/**"
      - ".github/workflows/**"

jobs:
  pipeline:
    uses: wellingtonns/templates-pipeline/.github/workflows/app-pipeline.yml@main
    with:
      app_name: app-clinica
      stack_type: frontend
      context: app-clinica
      image_name: ghcr.io/${{ github.repository_owner }}/app-clinica
      kustomize_repository: wellingtonns/kustomize-share
      kustomize_path: app/app-clinica
      image_alias: app-image
      update_kustomize: ${{ github.event_name == 'workflow_dispatch' && inputs.update_kustomize || github.event_name != 'workflow_dispatch' }}
      deploy: ${{ github.event_name == 'workflow_dispatch' && inputs.deploy || github.event_name != 'workflow_dispatch' }}
      deploy_ref: main
    secrets: inherit
