name: Secret Scan Example

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  secret-scan:
    uses: wellingtonns/templates-pipeline/.github/workflows/secret-scan.yml@main
    with:
      scan_path: .
      fail_on_leak: true
      run_gitleaks: true
      run_trufflehog: true
