name: branch-check

on:
  workflow_call:

jobs:
  branch-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Fetch main branch
        run: git fetch origin main --no-tags

      - name: Check if branch is up to date with main
        run: |
          MAIN=$(git rev-parse origin/main)
          BASE=$(git merge-base HEAD origin/main)

          if [ "$MAIN" != "$BASE" ]; then
            echo "Branch is not up to date with the main branch."
            exit 1
          fi