---
name: Build Docker image
on:
  workflow_call:
    inputs:
      ACR_REGISTRY:
        required: false
        type: string
        default: collegiaregistryhub.azurecr.io
      IMAGE_REPOSITORY:
        required: true
        type: string
      GCR_REGISTRY:
        required: false
        type: string
        default: europe-west2-docker.pkg.dev/collegia-infra-hub/collegia
      CONTEXT_DIR:
        required: false
        type: string
        default: .
      APPLICATION:
        required: false
        type: string
      ENVIRONMENT:
        required: false
        type: string
        default: dev
      AZ_REGION:
        required: false
        type: string
        default: "UK South"
      DOCKER_FILE_NAME:
        required: false
        type: string
        default: Dockerfile

env:
  ACR_REGISTRY: ${{ inputs.ACR_REGISTRY }}
  IMAGE_REPOSITORY: ${{ inputs.IMAGE_REPOSITORY }}
  GCR_REGISTRY: ${{ inputs.GCR_REGISTRY }}
  GCR_REPOSITORY: ${{ inputs.IMAGE_REPOSITORY }}
  CONTEXT_DIR: ${{ inputs.CONTEXT_DIR }}
  ENVIRONMENT: ${{ inputs.ENVIRONMENT }}
  APPLICATION: ${{ inputs.APPLICATION }}
  AZ_REGION: ${{ inputs.AZ_REGION }}
  DOCKER_FILE_NAME: ${{ inputs.DOCKER_FILE_NAME }}

permissions: 
  id-token: write
  contents: read

jobs:
  deploy:
    name: docker
    runs-on: ubuntu-latest
    environment: 
      name: ${{ inputs.ENVIRONMENT }}
    steps:
      - name: Check environment for branch
        run: |
          if [[ $GITHUB_REF_NAME != 'main' && $ENVIRONMENT == "prd" ]]; then
              echo "Deploy on Production environment is only allowed from main branch"
              exit 1
          else
              echo "Deploying on $environment environment from $GITHUB_REF_NAME branch"
          fi
      - name: Checkout
        uses: actions/checkout@v6
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: 'google-github-actions/auth@v2'
        id: gcp-auth
        with:
          token_format: access_token
          project_id: "collegia-infra-hub"
          workload_identity_provider: 'projects/1068935068736/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
          service_account: 'github-actions-user@collegia-infra-hub.iam.gserviceaccount.com'
 
      - name: Login to GCR
        uses: docker/login-action@v3
        with:
          registry: europe-west2-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.gcp-auth.outputs.access_token }}

      - name: Build, tag, and push image to GCR
        id: build-image-gcr
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: |
          cd ${{ env.CONTEXT_DIR }}
          docker build \
            -t $GCR_REGISTRY/$GCR_REPOSITORY:$IMAGE_TAG \
            -f ${{ env.DOCKER_FILE_NAME }} \
            --build-arg APP_ENV=${{ env.ENVIRONMENT }} \
            --build-arg GITHUB_TOKEN=${{ secrets.AUTOMATED_GIAN_TOKEN }} \
            .
          docker push $GCR_REGISTRY/$GCR_REPOSITORY:$IMAGE_TAG
          docker tag $GCR_REGISTRY/$GCR_REPOSITORY:$IMAGE_TAG $GCR_REGISTRY/$GCR_REPOSITORY:latest-$ENVIRONMENT
          docker push $GCR_REGISTRY/$GCR_REPOSITORY:latest-$ENVIRONMENT
          echo "image=$GCR_REGISTRY/$GCR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT

      # - name: Slack Notification
      #   if: failure()
      #   uses: rtCamp/action-slack-notify@v2
      #   env:
      #     SLACK_WEBHOOK: ${{ secrets.PIPELINE_SLACK_WEBHOOK }}
      #     SLACK_CHANNEL: pipelines
      #     SLACK_COLOR: ${{ job.status }} # or a specific color like 'good' or '#ff00ff'
      #     SLACK_ICON: https://avatars.githubusercontent.com/u/180990500?s=400&u=d9246676bf5b59f7dd6e6e97d90884560cad81fe&v=4
      #     SLACK_MESSAGE: '${{ env.APPLICATION }} deploy commit ${{ github.sha }}'
      #     SLACK_TITLE: 'Build ${{ env.APPLICATION }} ${{ env.ENVIRONMENT }}' 
      #     SLACK_USERNAME: Collegia-Bot
      #     SLACK_FOOTER: Triggered using collegia-bot and semantic version action
      #     SLACK_MESSAGE_ON_FAILURE: 'Build ${{ env.APPLICATION }} on environment ${{ env.ENVIRONMENT }} failed'
      #     SLACK_MESSAGE_ON_SUCCESS: 'Build ${{ env.APPLICATION }} on environment ${{ env.ENVIRONMENT }} success'
      #     SLACK_MESSAGE_ON_CANCEL: 'Build ${{ env.APPLICATION }} on environment ${{ env.ENVIRONMENT }} cancelled'
